[config]
[[databases]]
# 数据库名
name="enterprise"
# 数据库类型: mysql/postgres/sqlite/mssql
schema="mysql"
# 数据源名称
dsn="root:123456@tcp(127.0.0.1:3306)/enterprise?charset=utf8mb4"
	[[databases.tables]]
	# 数据表名称
	name="users"
	# 数据库主键名称
	primaryKey="id"
	# 索引字段
	index=["phone"]
	# 缓存条件
	# ALL: 所有记录 UPDATED_DAY: 一天内创建/更新的记录 UPDATED_WEEK: 一周内创建/更新的记录 UPDATED_MONTH: 一个月内创建/更新的记录(大小写无关)
    conditions=["UPDATED_DAY"]

    [[databases.tables]]
    name="devices"
    primaryKey="id"
    index=["user_id", "auth_key_id"]
    conditions=["UPDATED_DAY"]
